/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Anchor: typeof import('./../components/anchor/index.vue')['default']
    BackgroundImage: typeof import('./../components/background-image/index.vue')['default']
    ElAffix: typeof import('element-plus/es')['ElAffix']
    ElAnchor: typeof import('element-plus/es')['ElAnchor']
    ElAnchorLink: typeof import('element-plus/es')['ElAnchorLink']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTimeline: typeof import('element-plus/es')['ElTimeline']
    ElTimelineItem: typeof import('element-plus/es')['ElTimelineItem']
    HeaderBar: typeof import('./../layouts/header-bar/index.vue')['default']
    HeaderBg: typeof import('./../layouts/header-bg/index.vue')['default']
    Menu: typeof import('./../components/menu/index.vue')['default']
    PageBg: typeof import('./../layouts/page-bg/index.vue')['default']
    PageContainer: typeof import('./../layouts/page-container/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./../components/search-bar/index.vue')['default']
    SvgIcon: typeof import('./../components/svg-icon/index.vue')['default']
    TreeAnchor: typeof import('./../components/anchor/widget/TreeAnchor.vue')['default']
    TreeMenu: typeof import('./../components/menu/widget/TreeMenu.vue')['default']
    Wave: typeof import('./../components/wave/index.vue')['default']
  }
}
